FROM node:lts-alpine

WORKDIR /app
COPY . /app

ARG VITE_APP_RELEASE
ARG VITE_GIT_COMMIT_HASH

# Venue-specific parameters to be injected at runtime
ENV VITE_API_URL=PLACEHOLDER_API_URL
ENV VITE_MANGO_DOCS_URL=PLACEHOLDER_MANGO_DOCS_URL

ENV VITE_APP_TITLE=MANGO
ENV VITE_APP_PATH=/mango/

ENV VITE_APP_RELEASE=${VITE_APP_RELEASE}
ENV VITE_GIT_COMMIT_HASH=${VITE_GIT_COMMIT_HASH}

RUN npm i
RUN npm run build:force

# API
EXPOSE 8000

# UI
EXPOSE 5174

ENTRYPOINT ["./entrypoint.sh"]

CMD [ "npm", "run", "preview" ]
